### PR TITLE
Coordinate merge(pris, webscrape)

### LINKED ISSUE #40: Fix conflict between Webscrape and PRIS data (US)
Pris database file lists reactors.
Webscrape lists power plants but not reactors.

Thus, a python script to match reactors to their powerplant should be written for the US region.

### PR DESCRIPTION
**Pull request by gyutaepark**
This PR should be reviewed after #42.
`merge_coordinates.py` was written and run to merge coordinate information from webscrape (https://github.com/arfc/webscraping), and PRIS (`reactors_pris_2016.csv`).

Original pris csv file have been renamed to `reactors_pris_2016.original.csv`
Modified pris csv file used for merging is renamed to `reactors_pris_2016.modified.csv`
Resulting csv file with PRIS data and coordinates is named as `reactors_pris_2016.csv`.

This PR resolves #40 once merged.

### CODE REVIEW

**Comment by katyhuff** [comment]
@jbae11 , can you review this ?

**Comment by jbae11** [comment]
@gyutaepark @katyhuff Awesome work! However, it seems like the previous PR #42 has not been merged yet. Also, looking at the large number of files changed, Professor Huff's comment of not having the generated files in the repository are not reflected. Please do ping me again once these two things are done! Thanks!

**Comment by katyhuff** [comment]
This still seems to have some conflicts (see import_data/reactors_pris_2016.csv)

**Comment by gyutaepark** [comment]
@jbae11 I agree. 
The script uses `reactors_pris_2016.modified.csv` at this moment to produce `reactors_pris_2016.csv`.
This was a bad workflow decision that I've made in the past. 
I will create an isse and a PR that should be merged into this PR to fix this.

I agree that we should be using the `reactors_pris_2016.original.csv` to produce the output.

**Comment by gyutaepark** [comment]
@jbae11 The aforementioned comment has been now implemented in this PR.
Is this now ready for merge? Or do you need to review the PR further?

**Comment by jbae11** [comment]
@gyutaepark  Thank you for your work. I think it's ready to merge now!

**Comment by gyutaepark** [comment]
Approved and merged

**Pull request merged**
